### ISSUE TITLE
"Koodikoulu ensiaskeleet" and "Koodikoulu iltis" are not proper Finnish grammar

### ISSUE THREAD

**Issue by olliahonen** [koodikoulu/koodikoulu.fi#2]
The form should be "Koodikoulun ensiaskeleet" or "Koodikoulu-ensiaskeleet". I think it's super important to promote good Finnish especially for the children.

**Comment by rjoonas** [comment]
Agreed. I quite like ”Koodikoulun ensiaskeleet” & ”Koodikoulun iltis”.

**Comment by vtainio** [comment]
Thanks for the suggestion!
